### ISSUE TITLE
Password Resetting

### ISSUE THREAD

**Issue by JeuTheIdit** [masari-project/masari-wallet-gui#6]
Some users are reporting that upon re-entering the wallet after setting it up for the first time or restoring from seed, their password is defaulted to no password.

Happening with people running a local and remote node.

(I have not encountered this issue, just starting this thread in case we want to fix these issues even though the GUI is being dropped most likely by the web wallet)

**Comment by cryptochangements34** [comment]
masari-project/masari@a3734170 and masari-project/masari@6b5b2203 address this
